version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=startdb
      - POSTGRES_USER=iabd
      - POSTGRES_PASSWORD=4321
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"

volumes:
  postgres_data: